# Detalhes da versão a ser liberada
---
title: v1.2
apiKey: SWCGE-FEV8C-1CC9X-7OC0O
releaseNotesFile: release-notes.md
buildDirectory: target
artifacts:
  - software-delivery-maven-plugin-0.0.1-SNAPSHOT.jar
