# Detalhes da versão a ser liberada
---
title: v1.5
releaseNotesFile: release-notes.md
artifactDirectory: target
artifacts:
  - software-delivery-maven-plugin-0.0.1.jar
  - maven-archiver/pom.properties