# Detalhes da versão a ser liberada
---
title: v1.0.12
apiKey: OWX4M-XIH13-0X333-QB0QO
releaseNotesFile: release-notes.md
buildDirectory: target
artifacts:
  - software-delivery-maven-plugin-0.0.1-SNAPSHOT.jar
